- name: ensure IP forward bit is activated
  sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes

- name: ensure IPv4 rp filter is deactivated
  sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present reload=yes

- name: ensure IPv4 default rp filter is deactivated
  sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present reload=yes
    
- name: ensure plugins, agents and openvswitch packages are installed
  apt: name={{ item }} 
  with_items:
    - neutron-common
    - neutron-openvswitch-agent
    - neutron-metadata-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-lbaasv2-agent