- name: ensure IPv4 rp filter is deactivated
  sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present reload=yes

- name: ensure IPv4 default rp filter is deactivated
  sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present reload=yes


- name: ensure plugins, agents and openvswitch packages are installed
  apt: name={{ item }}
  with_items:
    - neutron-common
    - neutron-openvswitch-agent

- name: ensure neutron.conf is configured
  template: >
    src=../../neutronserver/templates/etc/neutron/neutron.conf
    dest=/etc/neutron/neutron.conf
    owner=neutron group=neutron mode=0660
  notify:
    - restart neutron agents

- name: ensure openvswitch plugin is configured
  template: >
    src=etc/neutron/plugins/ml2/openvswitch_agent.ini
    dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
    owner=root group=root mode=0644
  notify:
    - restart neutron agents

- name: ensure br-int switch is created
  openvswitch_bridge: bridge=br-int state=present fail_mode=secure
  notify: restart neutron agents
